#include <stdio.h>
#include <string.h>

#define FILE_NAME_MAX_LEN 50
#define POKEMON_NUM 718
#define POKEMON_NAME_MAX_LEN 20
#define PROPERTY_MAX_LEN 20

char pokemon[POKEMON_NUM][POKEMON_NAME_MAX_LEN + PROPERTY_MAX_LEN];

int main(void) {
	int pokemonNum;

	initPokemon();

	scanf("%d", &pokemonNum);
	
	printf("%s\n", pokemon[pokemonNum - 1]);

	return 0;
}

int initPokemon() {
	strcpy(pokemon[0], "Bulbasaur\nGrass Poison");
	strcpy(pokemon[1], "Ivysaur\nGrass Poison");
	strcpy(pokemon[2], "Venusaur\nGrass Poison");
	strcpy(pokemon[3], "Charmander\nFire");
	strcpy(pokemon[4], "Charmeleon\nFire");
	strcpy(pokemon[5], "Charizard\nFire Flying");
	strcpy(pokemon[6], "Squirtle\nWater");
	strcpy(pokemon[7], "Wartortle\nWater");
	strcpy(pokemon[8], "Blastoise\nWater");
	strcpy(pokemon[9], "Caterpie\nBug");
	strcpy(pokemon[10], "Metapod\nBug");
	strcpy(pokemon[11], "Butterfree\nBug Flying");
	strcpy(pokemon[12], "Weedle\nBug Poison");
	strcpy(pokemon[13], "Kakuna\nBug Poison");
	strcpy(pokemon[14], "Beedrill\nBug Poison");
	strcpy(pokemon[15], "Pidgey\nNormal Flying");
	strcpy(pokemon[16], "Pidgeotto\nNormal Flying");
	strcpy(pokemon[17], "Pidgeot\nNormal Flying");
	strcpy(pokemon[18], "Rattata\nNormal");
	strcpy(pokemon[19], "Raticate\nNormal");
	strcpy(pokemon[20], "Spearow\nNormal Flying");
	strcpy(pokemon[21], "Fearow\nNormal Flying");
	strcpy(pokemon[22], "Ekans\nPoison");
	strcpy(pokemon[23], "Arbok\nPoison");
	strcpy(pokemon[24], "Pikachu\nElectric");
	strcpy(pokemon[25], "Raichu\nElectric");
	strcpy(pokemon[26], "Sandshrew\nGround");
	strcpy(pokemon[27], "Sandslash\nGround");
	strcpy(pokemon[28], "Nidoran♀\nPoison");
	strcpy(pokemon[29], "Nidorina\nPoison");
	strcpy(pokemon[30], "Nidoqueen\nPoison Ground");
	strcpy(pokemon[31], "Nidoran♂\nPoison");
	strcpy(pokemon[32], "Nidorino\nPoison");
	strcpy(pokemon[33], "Nidoking\nPoison Ground");
	strcpy(pokemon[34], "Clefairy\nFairy");
	strcpy(pokemon[35], "Clefable\nFairy");
	strcpy(pokemon[36], "Vulpix\nFire");
	strcpy(pokemon[37], "Ninetales\nFire");
	strcpy(pokemon[38], "Jigglypuff\nNormal Fairy");
	strcpy(pokemon[39], "Wigglytuff\nNormal Fairy");
	strcpy(pokemon[40], "Zubat\nPoison Flying");
	strcpy(pokemon[41], "Golbat\nPoison Flying");
	strcpy(pokemon[42], "Oddish\nGrass Poison");
	strcpy(pokemon[43], "Gloom\nGrass Poison");
	strcpy(pokemon[44], "Vileplume\nGrass Poison");
	strcpy(pokemon[45], "Paras\nBug Grass");
	strcpy(pokemon[46], "Parasect\nBug Grass");
	strcpy(pokemon[47], "Venonat\nBug Poison");
	strcpy(pokemon[48], "Venomoth\nBug Poison");
	strcpy(pokemon[49], "Diglett\nGround");
	strcpy(pokemon[50], "Dugtrio\nGround");
	strcpy(pokemon[51], "Meowth\nNormal");
	strcpy(pokemon[52], "Persian\nNormal");
	strcpy(pokemon[53], "Psyduck\nWater");
	strcpy(pokemon[54], "Golduck\nWater");
	strcpy(pokemon[55], "Mankey\nFighting");
	strcpy(pokemon[56], "Primeape\nFighting");
	strcpy(pokemon[57], "Growlithe\nFire");
	strcpy(pokemon[58], "Arcanine\nFire");
	strcpy(pokemon[59], "Poliwag\nWater");
	strcpy(pokemon[60], "Poliwhirl\nWater");
	strcpy(pokemon[61], "Poliwrath\nWater Fighting");
	strcpy(pokemon[62], "Abra\nPsychic");
	strcpy(pokemon[63], "Kadabra\nPsychic");
	strcpy(pokemon[64], "Alakazam\nPsychic");
	strcpy(pokemon[65], "Machop\nFighting");
	strcpy(pokemon[66], "Machoke\nFighting");
	strcpy(pokemon[67], "Machamp\nFighting");
	strcpy(pokemon[68], "Bellsprout\nGrass Poison");
	strcpy(pokemon[69], "Weepinbell\nGrass Poison");
	strcpy(pokemon[70], "Victreebel\nGrass Poison");
	strcpy(pokemon[71], "Tentacool\nWater Poison");
	strcpy(pokemon[72], "Tentacruel\nWater Poison");
	strcpy(pokemon[73], "Geodude\nRock Ground");
	strcpy(pokemon[74], "Graveler\nRock Ground");
	strcpy(pokemon[75], "Golem\nRock Ground");
	strcpy(pokemon[76], "Ponyta\nFire");
	strcpy(pokemon[77], "Rapidash\nFire");
	strcpy(pokemon[78], "Slowpoke\nWater Psychic");
	strcpy(pokemon[79], "Slowbro\nWater Psychic");
	strcpy(pokemon[80], "Magnemite\nElectric Steel");
	strcpy(pokemon[81], "Magneton\nElectric Steel");
	strcpy(pokemon[82], "Farfetch'd\nNormal Flying");
	strcpy(pokemon[83], "Doduo\nNormal Flying");
	strcpy(pokemon[84], "Dodrio\nNormal Flying");
	strcpy(pokemon[85], "Seel\nWater");
	strcpy(pokemon[86], "Dewgong\nWater Ice");
	strcpy(pokemon[87], "Grimer\nPoison");
	strcpy(pokemon[88], "Muk\nPoison");
	strcpy(pokemon[89], "Shellder\nWater");
	strcpy(pokemon[90], "Cloyster\nWater Ice");
	strcpy(pokemon[91], "Gastly\nGhost Poison");
	strcpy(pokemon[92], "Haunter\nGhost Poison");
	strcpy(pokemon[93], "Gengar\nGhost Poison");
	strcpy(pokemon[94], "Onix\nRock Ground");
	strcpy(pokemon[95], "Drowzee\nPsychic");
	strcpy(pokemon[96], "Hypno\nPsychic");
	strcpy(pokemon[97], "Krabby\nWater");
	strcpy(pokemon[98], "Kingler\nWater");
	strcpy(pokemon[99], "Voltorb\nElectric");
	strcpy(pokemon[100], "Electrode\nElectric");
	strcpy(pokemon[101], "Exeggcute\nGrass Psychic");
	strcpy(pokemon[102], "Exeggutor\nGrass Psychic");
	strcpy(pokemon[103], "Cubone\nGround");
	strcpy(pokemon[104], "Marowak\nGround");
	strcpy(pokemon[105], "Hitmonlee\nFighting");
	strcpy(pokemon[106], "Hitmonchan\nFighting");
	strcpy(pokemon[107], "Lickitung\nNormal");
	strcpy(pokemon[108], "Koffing\nPoison");
	strcpy(pokemon[109], "Weezing\nPoison");
	strcpy(pokemon[110], "Rhyhorn\nGround Rock");
	strcpy(pokemon[111], "Rhydon\nGround Rock");
	strcpy(pokemon[112], "Chansey\nNormal");
	strcpy(pokemon[113], "Tangela\nGrass");
	strcpy(pokemon[114], "Kangaskhan\nNormal");
	strcpy(pokemon[115], "Horsea\nWater");
	strcpy(pokemon[116], "Seadra\nWater");
	strcpy(pokemon[117], "Goldeen\nWater");
	strcpy(pokemon[118], "Seaking\nWater");
	strcpy(pokemon[119], "Staryu\nWater");
	strcpy(pokemon[120], "Starmie\nWater Psychic");
	strcpy(pokemon[121], "Mr. Mime\nPsychic Fairy");
	strcpy(pokemon[122], "Scyther\nBug Flying");
	strcpy(pokemon[123], "Jynx\nIce Psychic");
	strcpy(pokemon[124], "Electabuzz\nElectric");
	strcpy(pokemon[125], "Magmar\nFire");
	strcpy(pokemon[126], "Pinsir\nBug");
	strcpy(pokemon[127], "Tauros\nNormal");
	strcpy(pokemon[128], "Magikarp\nWater");
	strcpy(pokemon[129], "Gyarados\nWater Flying");
	strcpy(pokemon[130], "Lapras\nWater Ice");
	strcpy(pokemon[131], "Ditto\nNormal");
	strcpy(pokemon[132], "Eevee\nNormal");
	strcpy(pokemon[133], "Vaporeon\nWater");
	strcpy(pokemon[134], "Jolteon\nElectric");
	strcpy(pokemon[135], "Flareon\nFire");
	strcpy(pokemon[136], "Porygon\nNormal");
	strcpy(pokemon[137], "Omanyte\nRock Water");
	strcpy(pokemon[138], "Omastar\nRock Water");
	strcpy(pokemon[139], "Kabuto\nRock Water");
	strcpy(pokemon[140], "Kabutops\nRock Water");
	strcpy(pokemon[141], "Aerodactyl\nRock Flying");
	strcpy(pokemon[142], "Snorlax\nNormal");
	strcpy(pokemon[143], "Articuno\nIce Flying");
	strcpy(pokemon[144], "Zapdos\nElectric Flying");
	strcpy(pokemon[145], "Moltres\nFire Flying");
	strcpy(pokemon[146], "Dratini\nDragon");
	strcpy(pokemon[147], "Dragonair\nDragon");
	strcpy(pokemon[148], "Dragonite\nDragon Flying");
	strcpy(pokemon[149], "Mewtwo\nPsychic");
	strcpy(pokemon[150], "Mew\nPsychic");
	strcpy(pokemon[151], "Chikorita\nGrass");
	strcpy(pokemon[152], "Bayleef\nGrass");
	strcpy(pokemon[153], "Meganium\nGrass");
	strcpy(pokemon[154], "Cyndaquil\nFire");
	strcpy(pokemon[155], "Quilava\nFire");
	strcpy(pokemon[156], "Typhlosion\nFire");
	strcpy(pokemon[157], "Totodile\nWater");
	strcpy(pokemon[158], "Croconaw\nWater");
	strcpy(pokemon[159], "Feraligatr\nWater");
	strcpy(pokemon[160], "Sentret\nNormal");
	strcpy(pokemon[161], "Furret\nNormal");
	strcpy(pokemon[162], "Hoothoot\nNormal Flying");
	strcpy(pokemon[163], "Noctowl\nNormal Flying");
	strcpy(pokemon[164], "Ledyba\nBug Flying");
	strcpy(pokemon[165], "Ledian\nBug Flying");
	strcpy(pokemon[166], "Spinarak\nBug Poison");
	strcpy(pokemon[167], "Ariados\nBug Poison");
	strcpy(pokemon[168], "Crobat\nPoison Flying");
	strcpy(pokemon[169], "Chinchou\nWater Electric");
	strcpy(pokemon[170], "Lanturn\nWater Electric");
	strcpy(pokemon[171], "Pichu\nElectric");
	strcpy(pokemon[172], "Cleffa\nFairy");
	strcpy(pokemon[173], "Igglybuff\nNormal Fairy");
	strcpy(pokemon[174], "Togepi\nFairy");
	strcpy(pokemon[175], "Togetic\nFairy Flying");
	strcpy(pokemon[176], "Natu\nPsychic Flying");
	strcpy(pokemon[177], "Xatu\nPsychic Flying");
	strcpy(pokemon[178], "Mareep\nElectric");
	strcpy(pokemon[179], "Flaaffy\nElectric");
	strcpy(pokemon[180], "Ampharos\nElectric");
	strcpy(pokemon[181], "Bellossom\nGrass");
	strcpy(pokemon[182], "Marill\nWater Fairy");
	strcpy(pokemon[183], "Azumarill\nWater Fairy");
	strcpy(pokemon[184], "Sudowoodo\nRock");
	strcpy(pokemon[185], "Politoed\nWater");
	strcpy(pokemon[186], "Hoppip\nGrass Flying");
	strcpy(pokemon[187], "Skiploom\nGrass Flying");
	strcpy(pokemon[188], "Jumpluff\nGrass Flying");
	strcpy(pokemon[189], "Aipom\nNormal");
	strcpy(pokemon[190], "Sunkern\nGrass");
	strcpy(pokemon[191], "Sunflora\nGrass");
	strcpy(pokemon[192], "Yanma\nBug Flying");
	strcpy(pokemon[193], "Wooper\nWater Ground");
	strcpy(pokemon[194], "Quagsire\nWater Ground");
	strcpy(pokemon[195], "Espeon\nPsychic");
	strcpy(pokemon[196], "Umbreon\nDark");
	strcpy(pokemon[197], "Murkrow\nDark Flying");
	strcpy(pokemon[198], "Slowking\nWater Psychic");
	strcpy(pokemon[199], "Misdreavus\nGhost");
	strcpy(pokemon[200], "Unown\nPsychic");
	strcpy(pokemon[201], "Wobbuffet\nPsychic");
	strcpy(pokemon[202], "Girafarig\nNormal Psychic");
	strcpy(pokemon[203], "Pineco\nBug");
	strcpy(pokemon[204], "Forretress\nBug Steel");
	strcpy(pokemon[205], "Dunsparce\nNormal");
	strcpy(pokemon[206], "Gligar\nGround Flying");
	strcpy(pokemon[207], "Steelix\nSteel Ground");
	strcpy(pokemon[208], "Snubbull\nFairy");
	strcpy(pokemon[209], "Granbull\nFairy");
	strcpy(pokemon[210], "Qwilfish\nWater Poison");
	strcpy(pokemon[211], "Scizor\nBug Steel");
	strcpy(pokemon[212], "Shuckle\nBug Rock");
	strcpy(pokemon[213], "Heracross\nBug Fighting");
	strcpy(pokemon[214], "Sneasel\nDark Ice");
	strcpy(pokemon[215], "Teddiursa\nNormal");
	strcpy(pokemon[216], "Ursaring\nNormal");
	strcpy(pokemon[217], "Slugma\nFire");
	strcpy(pokemon[218], "Magcargo\nFire Rock");
	strcpy(pokemon[219], "Swinub\nIce Ground");
	strcpy(pokemon[220], "Piloswine\nIce Ground");
	strcpy(pokemon[221], "Corsola\nWater Rock");
	strcpy(pokemon[222], "Remoraid\nWater");
	strcpy(pokemon[223], "Octillery\nWater");
	strcpy(pokemon[224], "Delibird\nIce Flying");
	strcpy(pokemon[225], "Mantine\nWater Flying");
	strcpy(pokemon[226], "Skarmory\nSteel Flying");
	strcpy(pokemon[227], "Houndour\nDark Fire");
	strcpy(pokemon[228], "Houndoom\nDark Fire");
	strcpy(pokemon[229], "Kingdra\nWater Dragon");
	strcpy(pokemon[230], "Phanpy\nGround");
	strcpy(pokemon[231], "Donphan\nGround");
	strcpy(pokemon[232], "Porygon2\nNormal");
	strcpy(pokemon[233], "Stantler\nNormal");
	strcpy(pokemon[234], "Smeargle\nNormal");
	strcpy(pokemon[235], "Tyrogue\nFighting");
	strcpy(pokemon[236], "Hitmontop\nFighting");
	strcpy(pokemon[237], "Smoochum\nIce Psychic");
	strcpy(pokemon[238], "Elekid\nElectric");
	strcpy(pokemon[239], "Magby\nFire");
	strcpy(pokemon[240], "Miltank\nNormal");
	strcpy(pokemon[241], "Blissey\nNormal");
	strcpy(pokemon[242], "Raikou\nElectric");
	strcpy(pokemon[243], "Entei\nFire");
	strcpy(pokemon[244], "Suicune\nWater");
	strcpy(pokemon[245], "Larvitar\nRock Ground");
	strcpy(pokemon[246], "Pupitar\nRock Ground");
	strcpy(pokemon[247], "Tyranitar\nRock Dark");
	strcpy(pokemon[248], "Lugia\nPsychic Flying");
	strcpy(pokemon[249], "Ho-oh\nFire Flying");
	strcpy(pokemon[250], "Celebi\nPsychic Grass");
	strcpy(pokemon[251], "Treecko\nGrass");
	strcpy(pokemon[252], "Grovyle\nGrass");
	strcpy(pokemon[253], "Sceptile\nGrass");
	strcpy(pokemon[254], "Torchic\nFire");
	strcpy(pokemon[255], "Combusken\nFire Fighting");
	strcpy(pokemon[256], "Blaziken\nFire Fighting");
	strcpy(pokemon[257], "Mudkip\nWater");
	strcpy(pokemon[258], "Marshtomp\nWater Ground");
	strcpy(pokemon[259], "Swampert\nWater Ground");
	strcpy(pokemon[260], "Poochyena\nDark");
	strcpy(pokemon[261], "Mightyena\nDark");
	strcpy(pokemon[262], "Zigzagoon\nNormal");
	strcpy(pokemon[263], "Linoone\nNormal");
	strcpy(pokemon[264], "Wurmple\nBug");
	strcpy(pokemon[265], "Silcoon\nBug");
	strcpy(pokemon[266], "Beautifly\nBug Flying");
	strcpy(pokemon[267], "Cascoon\nBug");
	strcpy(pokemon[268], "Dustox\nBug Poison");
	strcpy(pokemon[269], "Lotad\nWater Grass");
	strcpy(pokemon[270], "Lombre\nWater Grass");
	strcpy(pokemon[271], "Ludicolo\nWater Grass");
	strcpy(pokemon[272], "Seedot\nGrass");
	strcpy(pokemon[273], "Nuzleaf\nGrass Dark");
	strcpy(pokemon[274], "Shiftry\nGrass Dark");
	strcpy(pokemon[275], "Taillow\nNormal Flying");
	strcpy(pokemon[276], "Swellow\nNormal Flying");
	strcpy(pokemon[277], "Wingull\nWater Flying");
	strcpy(pokemon[278], "Pelipper\nWater Flying");
	strcpy(pokemon[279], "Ralts\nPsychic Fairy");
	strcpy(pokemon[280], "Kirlia\nPsychic Fairy");
	strcpy(pokemon[281], "Gardevoir\nPsychic Fairy");
	strcpy(pokemon[282], "Surskit\nBug Water");
	strcpy(pokemon[283], "Masquerain\nBug Flying");
	strcpy(pokemon[284], "Shroomish\nGrass");
	strcpy(pokemon[285], "Breloom\nGrass Fighting");
	strcpy(pokemon[286], "Slakoth\nNormal");
	strcpy(pokemon[287], "Vigoroth\nNormal");
	strcpy(pokemon[288], "Slaking\nNormal");
	strcpy(pokemon[289], "Nincada\nBug Ground");
	strcpy(pokemon[290], "Ninjask\nBug Flying");
	strcpy(pokemon[291], "Shedinja\nBug Ghost");
	strcpy(pokemon[292], "Whismur\nNormal");
	strcpy(pokemon[293], "Loudred\nNormal");
	strcpy(pokemon[294], "Exploud\nNormal");
	strcpy(pokemon[295], "Makuhita\nFighting");
	strcpy(pokemon[296], "Hariyama\nFighting");
	strcpy(pokemon[297], "Azurill\nNormal Fairy");
	strcpy(pokemon[298], "Nosepass\nRock");
	strcpy(pokemon[299], "Skitty\nNormal");
	strcpy(pokemon[300], "Delcatty\nNormal");
	strcpy(pokemon[301], "Sableye\nDark Ghost");
	strcpy(pokemon[302], "Mawile\nSteel Fairy");
	strcpy(pokemon[303], "Aron\nSteel Rock");
	strcpy(pokemon[304], "Lairon\nSteel Rock");
	strcpy(pokemon[305], "Aggron\nSteel Rock");
	strcpy(pokemon[306], "Meditite\nFighting Psychic");
	strcpy(pokemon[307], "Medicham\nFighting Psychic");
	strcpy(pokemon[308], "Electrike\nElectric");
	strcpy(pokemon[309], "Manectric\nElectric");
	strcpy(pokemon[310], "Plusle\nElectric");
	strcpy(pokemon[311], "Minun\nElectric");
	strcpy(pokemon[312], "Volbeat\nBug");
	strcpy(pokemon[313], "Illumise\nBug");
	strcpy(pokemon[314], "Roselia\nGrass Poison");
	strcpy(pokemon[315], "Gulpin\nPoison");
	strcpy(pokemon[316], "Swalot\nPoison");
	strcpy(pokemon[317], "Carvanha\nWater Dark");
	strcpy(pokemon[318], "Sharpedo\nWater Dark");
	strcpy(pokemon[319], "Wailmer\nWater");
	strcpy(pokemon[320], "Wailord\nWater");
	strcpy(pokemon[321], "Numel\nFire Ground");
	strcpy(pokemon[322], "Camerupt\nFire Ground");
	strcpy(pokemon[323], "Torkoal\nFire");
	strcpy(pokemon[324], "Spoink\nPsychic");
	strcpy(pokemon[325], "Grumpig\nPsychic");
	strcpy(pokemon[326], "Spinda\nNormal");
	strcpy(pokemon[327], "Trapinch\nGround");
	strcpy(pokemon[328], "Vibrava\nGround Dragon");
	strcpy(pokemon[329], "Flygon\nGround Dragon");
	strcpy(pokemon[330], "Cacnea\nGrass");
	strcpy(pokemon[331], "Cacturne\nGrass Dark");
	strcpy(pokemon[332], "Swablu\nNormal Flying");
	strcpy(pokemon[333], "Altaria\nDragon Flying");
	strcpy(pokemon[334], "Zangoose\nNormal");
	strcpy(pokemon[335], "Seviper\nPoison");
	strcpy(pokemon[336], "Lunatone\nRock Psychic");
	strcpy(pokemon[337], "Solrock\nRock Psychic");
	strcpy(pokemon[338], "Barboach\nWater Ground");
	strcpy(pokemon[339], "Whiscash\nWater Ground");
	strcpy(pokemon[340], "Corphish\nWater");
	strcpy(pokemon[341], "Crawdaunt\nWater Dark");
	strcpy(pokemon[342], "Baltoy\nGround Psychic");
	strcpy(pokemon[343], "Claydol\nGround Psychic");
	strcpy(pokemon[344], "Lileep\nRock Grass");
	strcpy(pokemon[345], "Cradily\nRock Grass");
	strcpy(pokemon[346], "Anorith\nRock Bug");
	strcpy(pokemon[347], "Armaldo\nRock Bug");
	strcpy(pokemon[348], "Feebas\nWater");
	strcpy(pokemon[349], "Milotic\nWater");
	strcpy(pokemon[350], "Castform\nNormal");
	strcpy(pokemon[351], "Kecleon\nNormal");
	strcpy(pokemon[352], "Shuppet\nGhost");
	strcpy(pokemon[353], "Banette\nGhost");
	strcpy(pokemon[354], "Duskull\nGhost");
	strcpy(pokemon[355], "Dusclops\nGhost");
	strcpy(pokemon[356], "Tropius\nGrass Flying");
	strcpy(pokemon[357], "Chimecho\nPsychic");
	strcpy(pokemon[358], "Absol\nDark");
	strcpy(pokemon[359], "Wynaut\nPsychic");
	strcpy(pokemon[360], "Snorunt\nIce");
	strcpy(pokemon[361], "Glalie\nIce");
	strcpy(pokemon[362], "Spheal\nIce Water");
	strcpy(pokemon[363], "Sealeo\nIce Water");
	strcpy(pokemon[364], "Walrein\nIce Water");
	strcpy(pokemon[365], "Clamperl\nWater");
	strcpy(pokemon[366], "Huntail\nWater");
	strcpy(pokemon[367], "Gorebyss\nWater");
	strcpy(pokemon[368], "Relicanth\nWater Rock");
	strcpy(pokemon[369], "Luvdisc\nWater");
	strcpy(pokemon[370], "Bagon\nDragon");
	strcpy(pokemon[371], "Shelgon\nDragon");
	strcpy(pokemon[372], "Salamence\nDragon Flying");
	strcpy(pokemon[373], "Beldum\nSteel Psychic");
	strcpy(pokemon[374], "Metang\nSteel Psychic");
	strcpy(pokemon[375], "Metagross\nSteel Psychic");
	strcpy(pokemon[376], "Regirock\nRock");
	strcpy(pokemon[377], "Regice\nIce");
	strcpy(pokemon[378], "Registeel\nSteel");
	strcpy(pokemon[379], "Latias\nDragon Psychic");
	strcpy(pokemon[380], "Latios\nDragon Psychic");
	strcpy(pokemon[381], "Kyogre\nWater");
	strcpy(pokemon[382], "Groudon\nGround");
	strcpy(pokemon[383], "Rayquaza\nDragon Flying");
	strcpy(pokemon[384], "Jirachi\nSteel Psychic");
	strcpy(pokemon[385], "Deoxys\nPsychic");
	strcpy(pokemon[386], "Turtwig\nGrass");
	strcpy(pokemon[387], "Grotle\nGrass");
	strcpy(pokemon[388], "Torterra\nGrass Ground");
	strcpy(pokemon[389], "Chimchar\nFire");
	strcpy(pokemon[390], "Monferno\nFire Fighting");
	strcpy(pokemon[391], "Infernape\nFire Fighting");
	strcpy(pokemon[392], "Piplup\nWater");
	strcpy(pokemon[393], "Prinplup\nWater");
	strcpy(pokemon[394], "Empoleon\nWater Steel");
	strcpy(pokemon[395], "Starly\nNormal Flying");
	strcpy(pokemon[396], "Staravia\nNormal Flying");
	strcpy(pokemon[397], "Staraptor\nNormal Flying");
	strcpy(pokemon[398], "Bidoof\nNormal");
	strcpy(pokemon[399], "Bibarel\nNormal Water");
	strcpy(pokemon[400], "Kricketot\nBug");
	strcpy(pokemon[401], "Kricketune\nBug");
	strcpy(pokemon[402], "Shinx\nElectric");
	strcpy(pokemon[403], "Luxio\nElectric");
	strcpy(pokemon[404], "Luxray\nElectric");
	strcpy(pokemon[405], "Budew\nGrass Poison");
	strcpy(pokemon[406], "Roserade\nGrass Poison");
	strcpy(pokemon[407], "Cranidos\nRock");
	strcpy(pokemon[408], "Rampardos\nRock");
	strcpy(pokemon[409], "Shieldon\nRock Steel");
	strcpy(pokemon[410], "Bastiodon\nRock Steel");
	strcpy(pokemon[411], "Burmy\nBug");
	strcpy(pokemon[412], "Wormadam\nBug Grass");
	strcpy(pokemon[413], "Mothim\nBug Flying");
	strcpy(pokemon[414], "Combee\nBug Flying");
	strcpy(pokemon[415], "Vespiquen\nBug Flying");
	strcpy(pokemon[416], "Pachirisu\nElectric");
	strcpy(pokemon[417], "Buizel\nWater");
	strcpy(pokemon[418], "Floatzel\nWater");
	strcpy(pokemon[419], "Cherubi\nGrass");
	strcpy(pokemon[420], "Cherrim\nGrass");
	strcpy(pokemon[421], "Shellos\nWater");
	strcpy(pokemon[422], "Gastrodon\nWater Ground");
	strcpy(pokemon[423], "Ambipom\nNormal");
	strcpy(pokemon[424], "Drifloon\nGhost Flying");
	strcpy(pokemon[425], "Drifblim\nGhost Flying");
	strcpy(pokemon[426], "Buneary\nNormal");
	strcpy(pokemon[427], "Lopunny\nNormal");
	strcpy(pokemon[428], "Mismagius\nGhost");
	strcpy(pokemon[429], "Honchkrow\nDark Flying");
	strcpy(pokemon[430], "Glameow\nNormal");
	strcpy(pokemon[431], "Purugly\nNormal");
	strcpy(pokemon[432], "Chingling\nPsychic");
	strcpy(pokemon[433], "Stunky\nPoison Dark");
	strcpy(pokemon[434], "Skuntank\nPoison Dark");
	strcpy(pokemon[435], "Bronzor\nSteel Psychic");
	strcpy(pokemon[436], "Bronzong\nSteel Psychic");
	strcpy(pokemon[437], "Bonsly\nRock");
	strcpy(pokemon[438], "Mime Jr.\nPsychic Fairy");
	strcpy(pokemon[439], "Happiny\nNormal");
	strcpy(pokemon[440], "Chatot\nNormal Flying");
	strcpy(pokemon[441], "Spiritomb\nGhost Dark");
	strcpy(pokemon[442], "Gible\nDragon Ground");
	strcpy(pokemon[443], "Gabite\nDragon Ground");
	strcpy(pokemon[444], "Garchomp\nDragon Ground");
	strcpy(pokemon[445], "Munchlax\nNormal");
	strcpy(pokemon[446], "Riolu\nFighting");
	strcpy(pokemon[447], "Lucario\nFighting Steel");
	strcpy(pokemon[448], "Hippopotas\nGround");
	strcpy(pokemon[449], "Hippowdon\nGround");
	strcpy(pokemon[450], "Skorupi\nPoison Bug");
	strcpy(pokemon[451], "Drapion\nPoison Dark");
	strcpy(pokemon[452], "Croagunk\nPoison Fighting");
	strcpy(pokemon[453], "Toxicroak\nPoison Fighting");
	strcpy(pokemon[454], "Carnivine\nGrass");
	strcpy(pokemon[455], "Finneon\nWater");
	strcpy(pokemon[456], "Lumineon\nWater");
	strcpy(pokemon[457], "Mantyke\nWater Flying");
	strcpy(pokemon[458], "Snover\nGrass Ice");
	strcpy(pokemon[459], "Abomasnow\nGrass Ice");
	strcpy(pokemon[460], "Weavile\nDark Ice");
	strcpy(pokemon[461], "Magnezone\nElectric Steel");
	strcpy(pokemon[462], "Lickilicky\nNormal");
	strcpy(pokemon[463], "Rhyperior\nGround Rock");
	strcpy(pokemon[464], "Tangrowth\nGrass");
	strcpy(pokemon[465], "Electivire\nElectric");
	strcpy(pokemon[466], "Magmortar\nFire");
	strcpy(pokemon[467], "Togekiss\nFairy Flying");
	strcpy(pokemon[468], "Yanmega\nBug Flying");
	strcpy(pokemon[469], "Leafeon\nGrass");
	strcpy(pokemon[470], "Glaceon\nIce");
	strcpy(pokemon[471], "Gliscor\nGround Flying");
	strcpy(pokemon[472], "Mamoswine\nIce Ground");
	strcpy(pokemon[473], "Porygon-Z\nNormal");
	strcpy(pokemon[474], "Gallade\nPsychic Fighting");
	strcpy(pokemon[475], "Probopass\nRock Steel");
	strcpy(pokemon[476], "Dusknoir\nGhost");
	strcpy(pokemon[477], "Froslass\nIce Ghost");
	strcpy(pokemon[478], "Rotom\nElectric Ghost");
	strcpy(pokemon[479], "Uxie\nPsychic");
	strcpy(pokemon[480], "Mesprit\nPsychic");
	strcpy(pokemon[481], "Azelf\nPsychic");
	strcpy(pokemon[482], "Dialga\nSteel Dragon");
	strcpy(pokemon[483], "Palkia\nWater Dragon");
	strcpy(pokemon[484], "Heatran\nFire Steel");
	strcpy(pokemon[485], "Regigigas\nNormal");
	strcpy(pokemon[486], "Giratina\nGhost Dragon");
	strcpy(pokemon[487], "Cresselia\nPsychic");
	strcpy(pokemon[488], "Phione\nWater");
	strcpy(pokemon[489], "Manaphy\nWater");
	strcpy(pokemon[490], "Darkrai\nDark");
	strcpy(pokemon[491], "Shaymin\nGrass");
	strcpy(pokemon[492], "Arceus\nNormal");
	strcpy(pokemon[493], "Victini\nPsychic Fire");
	strcpy(pokemon[494], "Snivy\nGrass");
	strcpy(pokemon[495], "Servine\nGrass");
	strcpy(pokemon[496], "Serperior\nGrass");
	strcpy(pokemon[497], "Tepig\nFire");
	strcpy(pokemon[498], "Pignite\nFire Fighting");
	strcpy(pokemon[499], "Emboar\nFire Fighting");
	strcpy(pokemon[500], "Oshawott\nWater");
	strcpy(pokemon[501], "Dewott\nWater");
	strcpy(pokemon[502], "Samurott\nWater");
	strcpy(pokemon[503], "Patrat\nNormal");
	strcpy(pokemon[504], "Watchog\nNormal");
	strcpy(pokemon[505], "Lillipup\nNormal");
	strcpy(pokemon[506], "Herdier\nNormal");
	strcpy(pokemon[507], "Stoutland\nNormal");
	strcpy(pokemon[508], "Purrloin\nDark");
	strcpy(pokemon[509], "Liepard\nDark");
	strcpy(pokemon[510], "Pansage\nGrass");
	strcpy(pokemon[511], "Simisage\nGrass");
	strcpy(pokemon[512], "Pansear\nFire");
	strcpy(pokemon[513], "Simisear\nFire");
	strcpy(pokemon[514], "Panpour\nWater");
	strcpy(pokemon[515], "Simipour\nWater");
	strcpy(pokemon[516], "Munna\nPsychic");
	strcpy(pokemon[517], "Musharna\nPsychic");
	strcpy(pokemon[518], "Pidove\nNormal Flying");
	strcpy(pokemon[519], "Tranquill\nNormal Flying");
	strcpy(pokemon[520], "Unfezant\nNormal Flying");
	strcpy(pokemon[521], "Blitzle\nElectric");
	strcpy(pokemon[522], "Zebstrika\nElectric");
	strcpy(pokemon[523], "Roggenrola\nRock");
	strcpy(pokemon[524], "Boldore\nRock");
	strcpy(pokemon[525], "Gigalith\nRock");
	strcpy(pokemon[526], "Woobat\nPsychic Flying");
	strcpy(pokemon[527], "Swoobat\nPsychic Flying");
	strcpy(pokemon[528], "Drilbur\nGround");
	strcpy(pokemon[529], "Excadrill\nGround Steel");
	strcpy(pokemon[530], "Audino\nNormal");
	strcpy(pokemon[531], "Timburr\nFighting");
	strcpy(pokemon[532], "Gurdurr\nFighting");
	strcpy(pokemon[533], "Conkeldurr\nFighting");
	strcpy(pokemon[534], "Tympole\nWater");
	strcpy(pokemon[535], "Palpitoad\nWater Ground");
	strcpy(pokemon[536], "Seismitoad\nWater Ground");
	strcpy(pokemon[537], "Throh\nFighting");
	strcpy(pokemon[538], "Sawk\nFighting");
	strcpy(pokemon[539], "Sewaddle\nBug Grass");
	strcpy(pokemon[540], "Swadloon\nBug Grass");
	strcpy(pokemon[541], "Leavanny\nBug Grass");
	strcpy(pokemon[542], "Venipede\nBug Poison");
	strcpy(pokemon[543], "Whirlipede\nBug Poison");
	strcpy(pokemon[544], "Scolipede\nBug Poison");
	strcpy(pokemon[545], "Cottonee\nGrass Fairy");
	strcpy(pokemon[546], "Whimsicott\nGrass Fairy");
	strcpy(pokemon[547], "Petilil\nGrass");
	strcpy(pokemon[548], "Lilligant\nGrass");
	strcpy(pokemon[549], "Basculin\nWater");
	strcpy(pokemon[550], "Sandile\nGround Dark");
	strcpy(pokemon[551], "Krokorok\nGround Dark");
	strcpy(pokemon[552], "Krookodile\nGround Dark");
	strcpy(pokemon[553], "Darumaka\nFire");
	strcpy(pokemon[554], "Darmanitan\nFire");
	strcpy(pokemon[555], "Maractus\nGrass");
	strcpy(pokemon[556], "Dwebble\nBug Rock");
	strcpy(pokemon[557], "Crustle\nBug Rock");
	strcpy(pokemon[558], "Scraggy\nDark Fighting");
	strcpy(pokemon[559], "Scrafty\nDark Fighting");
	strcpy(pokemon[560], "Sigilyph\nPsychic Flying");
	strcpy(pokemon[561], "Yamask\nGhost");
	strcpy(pokemon[562], "Cofagrigus\nGhost");
	strcpy(pokemon[563], "Tirtouga\nWater Rock");
	strcpy(pokemon[564], "Carracosta\nWater Rock");
	strcpy(pokemon[565], "Archen\nRock Flying");
	strcpy(pokemon[566], "Archeops\nRock Flying");
	strcpy(pokemon[567], "Trubbish\nPoison");
	strcpy(pokemon[568], "Garbodor\nPoison");
	strcpy(pokemon[569], "Zorua\nDark");
	strcpy(pokemon[570], "Zoroark\nDark");
	strcpy(pokemon[571], "Minccino\nNormal");
	strcpy(pokemon[572], "Cinccino\nNormal");
	strcpy(pokemon[573], "Gothita\nPsychic");
	strcpy(pokemon[574], "Gothorita\nPsychic");
	strcpy(pokemon[575], "Gothitelle\nPsychic");
	strcpy(pokemon[576], "Solosis\nPsychic");
	strcpy(pokemon[577], "Duosion\nPsychic");
	strcpy(pokemon[578], "Reuniclus\nPsychic");
	strcpy(pokemon[579], "Ducklett\nWater Flying");
	strcpy(pokemon[580], "Swanna\nWater Flying");
	strcpy(pokemon[581], "Vanillite\nIce");
	strcpy(pokemon[582], "Vanillish\nIce");
	strcpy(pokemon[583], "Vanilluxe\nIce");
	strcpy(pokemon[584], "Deerling\nNormal Grass");
	strcpy(pokemon[585], "Sawsbuck\nNormal Grass");
	strcpy(pokemon[586], "Emolga\nElectric Flying");
	strcpy(pokemon[587], "Karrablast\nBug");
	strcpy(pokemon[588], "Escavalier\nBug Steel");
	strcpy(pokemon[589], "Foongus\nGrass Poison");
	strcpy(pokemon[590], "Amoonguss\nGrass Poison");
	strcpy(pokemon[591], "Frillish\nWater Ghost");
	strcpy(pokemon[592], "Jellicent\nWater Ghost");
	strcpy(pokemon[593], "Alomomola\nWater");
	strcpy(pokemon[594], "Joltik\nBug Electric");
	strcpy(pokemon[595], "Galvantula\nBug Electric");
	strcpy(pokemon[596], "Ferroseed\nGrass Steel");
	strcpy(pokemon[597], "Ferrothorn\nGrass Steel");
	strcpy(pokemon[598], "Klink\nSteel");
	strcpy(pokemon[599], "Klang\nSteel");
	strcpy(pokemon[600], "Klinklang\nSteel");
	strcpy(pokemon[601], "Tynamo\nElectric");
	strcpy(pokemon[602], "Eelektrik\nElectric");
	strcpy(pokemon[603], "Eelektross\nElectric");
	strcpy(pokemon[604], "Elgyem\nPsychic");
	strcpy(pokemon[605], "Beheeyem\nPsychic");
	strcpy(pokemon[606], "Litwick\nGhost Fire");
	strcpy(pokemon[607], "Lampent\nGhost Fire");
	strcpy(pokemon[608], "Chandelure\nGhost Fire");
	strcpy(pokemon[609], "Axew\nDragon");
	strcpy(pokemon[610], "Fraxure\nDragon");
	strcpy(pokemon[611], "Haxorus\nDragon");
	strcpy(pokemon[612], "Cubchoo\nIce");
	strcpy(pokemon[613], "Beartic\nIce");
	strcpy(pokemon[614], "Cryogonal\nIce");
	strcpy(pokemon[615], "Shelmet\nBug");
	strcpy(pokemon[616], "Accelgor\nBug");
	strcpy(pokemon[617], "Stunfisk\nElectric Ground");
	strcpy(pokemon[618], "Mienfoo\nFighting");
	strcpy(pokemon[619], "Mienshao\nFighting");
	strcpy(pokemon[620], "Druddigon\nDragon");
	strcpy(pokemon[621], "Golett\nGround Ghost");
	strcpy(pokemon[622], "Golurk\nGround Ghost");
	strcpy(pokemon[623], "Pawniard\nDark Steel");
	strcpy(pokemon[624], "Bisharp\nDark Steel");
	strcpy(pokemon[625], "Bouffalant\nNormal");
	strcpy(pokemon[626], "Rufflet\nNormal Flying");
	strcpy(pokemon[627], "Braviary\nNormal Flying");
	strcpy(pokemon[628], "Vullaby\nDark Flying");
	strcpy(pokemon[629], "Mandibuzz\nDark Flying");
	strcpy(pokemon[630], "Heatmor\nFire");
	strcpy(pokemon[631], "Durant\nBug Steel");
	strcpy(pokemon[632], "Deino\nDark Dragon");
	strcpy(pokemon[633], "Zweilous\nDark Dragon");
	strcpy(pokemon[634], "Hydreigon\nDark Dragon");
	strcpy(pokemon[635], "Larvesta\nBug Fire");
	strcpy(pokemon[636], "Volcarona\nBug Fire");
	strcpy(pokemon[637], "Cobalion\nSteel Fighting");
	strcpy(pokemon[638], "Terrakion\nRock Fighting");
	strcpy(pokemon[639], "Virizion\nGrass Fighting");
	strcpy(pokemon[640], "Tornadus\nFlying");
	strcpy(pokemon[641], "Thundurus\nElectric Flying");
	strcpy(pokemon[642], "Reshiram\nDragon Fire");
	strcpy(pokemon[643], "Zekrom\nDragon Electric");
	strcpy(pokemon[644], "Landorus\nGround Flying");
	strcpy(pokemon[645], "Kyurem\nDragon Ice");
	strcpy(pokemon[646], "Keldeo\nWater Fighting");
	strcpy(pokemon[647], "Meloetta\nNormal Psychic");
	strcpy(pokemon[648], "Genesect\nBug Steel");
	strcpy(pokemon[649], "Chespin\nGrass");
	strcpy(pokemon[650], "Quilladin\nGrass");
	strcpy(pokemon[651], "Chesnaught\nGrass Fighting");
	strcpy(pokemon[652], "Fennekin\nFire");
	strcpy(pokemon[653], "Braixen\nFire");
	strcpy(pokemon[654], "Delphox\nFire Psychic");
	strcpy(pokemon[655], "Froakie\nWater");
	strcpy(pokemon[656], "Frogadier\nWater");
	strcpy(pokemon[657], "Greninja\nWater Dark");
	strcpy(pokemon[658], "Bunnelby\nNormal");
	strcpy(pokemon[659], "Diggersby\nNormal Ground");
	strcpy(pokemon[660], "Fletchling\nNormal Flying");
	strcpy(pokemon[661], "Fletchinder\nFire Flying");
	strcpy(pokemon[662], "Talonflame\nFire Flying");
	strcpy(pokemon[663], "Scatterbug\nBug");
	strcpy(pokemon[664], "Spewpa\nBug");
	strcpy(pokemon[665], "Vivillon\nBug Flying");
	strcpy(pokemon[666], "Litleo\nFire Normal");
	strcpy(pokemon[667], "Pyroar\nFire Normal");
	strcpy(pokemon[668], "Flabébé\nFairy");
	strcpy(pokemon[669], "Floette\nFairy");
	strcpy(pokemon[670], "Florges\nFairy");
	strcpy(pokemon[671], "Skiddo\nGrass");
	strcpy(pokemon[672], "Gogoat\nGrass");
	strcpy(pokemon[673], "Pancham\nFighting");
	strcpy(pokemon[674], "Pangoro\nFighting Dark");
	strcpy(pokemon[675], "Furfrou\nNormal");
	strcpy(pokemon[676], "Espurr\nPsychic");
	strcpy(pokemon[677], "Meowstic\nPsychic");
	strcpy(pokemon[678], "Honedge\nSteel Ghost");
	strcpy(pokemon[679], "Doublade\nSteel Ghost");
	strcpy(pokemon[680], "Aegislash\nSteel Ghost");
	strcpy(pokemon[681], "Spritzee\nFairy");
	strcpy(pokemon[682], "Aromatisse\nFairy");
	strcpy(pokemon[683], "Swirlix\nFairy");
	strcpy(pokemon[684], "Slurpuff\nFairy");
	strcpy(pokemon[685], "Inkay\nDark Psychic");
	strcpy(pokemon[686], "Malamar\nDark Psychic");
	strcpy(pokemon[687], "Binacle\nRock Water");
	strcpy(pokemon[688], "Barbaracle\nRock Water");
	strcpy(pokemon[689], "Skrelp\nPoison Water");
	strcpy(pokemon[690], "Dragalge\nPoison Dragon");
	strcpy(pokemon[691], "Clauncher\nWater");
	strcpy(pokemon[692], "Clawitzer\nWater");
	strcpy(pokemon[693], "Helioptile\nElectric Normal");
	strcpy(pokemon[694], "Heliolisk\nElectric Normal");
	strcpy(pokemon[695], "Tyrunt\nRock Dragon");
	strcpy(pokemon[696], "Tyrantrum\nRock Dragon");
	strcpy(pokemon[697], "Amaura\nRock Ice");
	strcpy(pokemon[698], "Aurorus\nRock Ice");
	strcpy(pokemon[699], "Sylveon\nFairy");
	strcpy(pokemon[700], "Hawlucha\nFighting Flying");
	strcpy(pokemon[701], "Dedenne\nElectric Fairy");
	strcpy(pokemon[702], "Carbink\nRock Fairy");
	strcpy(pokemon[703], "Goomy\nDragon");
	strcpy(pokemon[704], "Sliggoo\nDragon");
	strcpy(pokemon[705], "Goodra\nDragon");
	strcpy(pokemon[706], "Klefki\nSteel Fairy");
	strcpy(pokemon[707], "Phantump\nGhost Grass");
	strcpy(pokemon[708], "Trevenant\nGhost Grass");
	strcpy(pokemon[709], "Pumpkaboo\nGhost Grass");
	strcpy(pokemon[710], "Gourgeist\nGhost Grass");
	strcpy(pokemon[711], "Bergmite\nIce");
	strcpy(pokemon[712], "Avalugg\nIce");
	strcpy(pokemon[713], "Noibat\nFlying Dragon");
	strcpy(pokemon[714], "Noivern\nFlying Dragon");
	strcpy(pokemon[715], "Xerneas\nFairy");
	strcpy(pokemon[716], "Yveltal\nDark Flying");
	strcpy(pokemon[717], "Zygarde\nDragon Ground");

	return 0;
}


	
